disabled_rules:
  - line_length
  - trailing_comma
  - compiler_protocol_init
  - todo
  - file_length
  - nesting
  - colon
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - discarded_notification_center_observer
  - shorthand_operator
  - function_parameter_count
  - type_name

opt_in_rules:
  - force_unwrapping

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 50

force_unwrapping: error

trailing_whitespace:
  ignores_empty_lines: true

included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Example
  - Tests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Sources/NablaCore/Vendors
  - Sources/NablaCore/Data/GQL/Generated
  - Sources/NablaMessagingCore/Generated
  - Sources/NablaMessagingCore/Data/GQL/Generated
  - Sources/NablaMessagingCore/Vendors
  - Sources/NablaMessagingUI/Generated
  - Sources/NablaScheduling/Generated
  - Sources/NablaScheduling/Data/GQL/Generated
  - Tests/NablaCoreTestsUtils/Generated
  - Tests/NablaMessagingCoreTestsUtils/Generated
  - Tests/NablaMessagingUITests/Generated
  - Tests/NablaSchedulingTests/Generated
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging)

custom_rules:
  mutable_theme_properties:
    included: '(Theme|Theme\+.*).swift'
    regex: '(public static let)|(public let)'
    message: "All public theme properties must be mutable"
    severity: error